// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WissenTours.Persistence;

namespace WissenTours.Persistence.Migrations
{
    [DbContext(typeof(WissenToursDbContext))]
    partial class WissenToursDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WissenTours.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elazığ"
                        });
                });

            modelBuilder.Entity("WissenTours.Domain.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Esenler Otogarı"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Harem Otogarı"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Sakarya Büyükşehir Terminali"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Name = "Antalya Otogarı"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "Ankara Otogarı"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            Name = "Elazığ Otogarı"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Name = "Kaş Otogarı"
                        });
                });

            modelBuilder.Entity("WissenTours.Domain.Station", b =>
                {
                    b.HasOne("WissenTours.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
